stages:
  - sync

sync_with_github:
  stage: sync
  script:
    - echo "Configurando acceso a GitHub..."
    - |
        if git remote | grep -q "github"; then
          echo "Remoto github ya existe, actualizando URL..."
          git remote set-url github https://oauth2:${GITHUB_TOKEN}@github.com/rcacunar/deployNovedadesCBT.git
        else
          echo "Agregando remoto github..."
          git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/rcacunar/deployNovedadesCBT.git
        fi
    - echo "Obteniendo cambios más recientes de GitLab..."
    - git fetch origin
    - git checkout main  # Asegura estar en la rama correcta
    - git pull origin main  # Trae los últimos cambios de GitLab
    - echo "Empujando cambios a GitHub..."
    - git push github main  # Solo push a la rama main
    - git push github --tags  # Sincroniza etiquetas
  only:
    - main
